In [5]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import box
import math

# Define the AOI (minlon, minlat, maxlon, maxlat)
#aoi = {'minlon': -104.6450, 'minlat': 40.5002, 'maxlon': -105.5754, 'maxlat': 40.3092}

aoi = {
    'minlon': -125.0,
    'minlat': 32.0,
    'maxlon': -102.0,
    'maxlat': 49.0
}

# Calculate the width and height of the AOI in degrees
width = aoi['maxlon'] - aoi['minlon']
height = aoi['minlat'] - aoi['maxlat']

# Define the grid size in degrees (100 km converted to degrees, rough approximation)
grid_size_deg = 100 / 111.0  # Approximate conversion

# Calculate the number of grid cells in each dimension
n_cols = math.ceil(abs(width) / grid_size_deg)
n_rows = math.ceil(abs(height) / grid_size_deg)

# Generate the grid cells
grid_cells = []
for i in range(n_cols):
    for j in range(n_rows):
        minlon = aoi['minlon'] + i * grid_size_deg
        maxlon = min(minlon + grid_size_deg, aoi['maxlon'])
        minlat = aoi['minlat'] - j * grid_size_deg
        maxlat = max(minlat - grid_size_deg, aoi['maxlat'])
        
        grid_cells.append(box(minlon, maxlat, maxlon, minlat))

# Create a GeoDataFrame with the grid cells
grid_gdf = gpd.GeoDataFrame({'geometry': grid_cells}, crs='EPSG:4326')

In [6]:
grid_gdf

                                              geometry
0    POLYGON ((-124.09910 49.00000, -124.09910 32.0...
1    POLYGON ((-124.09910 49.00000, -124.09910 31.0...
2    POLYGON ((-124.09910 49.00000, -124.09910 30.1...
3    POLYGON ((-124.09910 49.00000, -124.09910 29.2...
4    POLYGON ((-124.09910 49.00000, -124.09910 28.3...
..                                                 ...
489  POLYGON ((-102.00000 49.00000, -102.00000 19.3...
490  POLYGON ((-102.00000 49.00000, -102.00000 18.4...
491  POLYGON ((-102.00000 49.00000, -102.00000 17.5...
492  POLYGON ((-102.00000 49.00000, -102.00000 16.6...
493  POLYGON ((-102.00000 49.00000, -102.00000 15.7...

[494 rows x 1 columns]